
    create table Disponibilidad (
        idDisponibilidad bigint generated by default as identity (start with 1),
        horarioFinal varbinary(255),
        horarioInicial varbinary(255),
        primary key (idDisponibilidad)
    )

    create table Disponibilidad_dias (
        Disponibilidad_idDisponibilidad bigint not null,
        dias varchar(255)
    )

    create table Domicilio (
        domicilioID bigint generated by default as identity (start with 1),
        alturaCalles integer not null,
        alturaPrincipal integer not null,
        callePrincipal varchar(255),
        codigoPostal integer not null,
        departamento integer not null,
        entreUnaCalle varchar(255),
        hastaOtraCalle varchar(255),
        piso integer not null,
        unidad integer not null,
        primary key (domicilioID)
    )

    create table POIS (
        poiID bigint generated by default as identity (start with 1),
        nombre varchar(255),
        ubicacion_ubicacionID bigint,
        primary key (poiID)
    )

    create table POIS_Disponibilidad (
        POIS_poiID bigint not null,
        horariosDeAtencion_idDisponibilidad bigint not null
    )

    create table PalabrasClave (
        Poi_poiID bigint not null,
        palabrasClave varchar(255)
    )

    create table Region (
        RegionID bigint generated by default as identity (start with 1),
        barrio varchar(255),
        localidad varchar(255),
        pais varchar(255),
        provincia varchar(255),
        primary key (RegionID)
    )

    create table ServiciosCGP (
        idServicioCGP bigint generated by default as identity (start with 1),
        nombre varchar(255),
        primary key (idServicioCGP)
    )

    create table ServiciosCGP_Disponibilidad (
        ServiciosCGP_idServicioCGP bigint not null,
        horariosDeAtencion_idDisponibilidad bigint not null
    )

    create table Terminales (
        terminalID bigint generated by default as identity (start with 1),
        comunaTerminal varchar(255),
        coordenadaDispositivoMovil varchar(255),
        nombreTerminal varchar(255),
        primary key (terminalID)
    )

    create table Ubicacion (
        ubicacionID bigint generated by default as identity (start with 1),
        coordenadas varchar(255),
        domicilio_domicilioID bigint,
        region_RegionID bigint,
        primary key (ubicacionID)
    )

    alter table POIS_Disponibilidad 
        add constraint UK_m1584286pc1qex6xcg46k0bcl  unique (horariosDeAtencion_idDisponibilidad)

    alter table ServiciosCGP_Disponibilidad 
        add constraint UK_sc7sk0ooswmxqt8swjv4sc97v  unique (horariosDeAtencion_idDisponibilidad)

    alter table Disponibilidad_dias 
        add constraint FK_qth5ywka3bsues0par91w9l9c 
        foreign key (Disponibilidad_idDisponibilidad) 
        references Disponibilidad

    alter table POIS 
        add constraint FK_rq1bh6ctglte2ju8jb84o0ky1 
        foreign key (ubicacion_ubicacionID) 
        references Ubicacion

    alter table POIS_Disponibilidad 
        add constraint FK_m1584286pc1qex6xcg46k0bcl 
        foreign key (horariosDeAtencion_idDisponibilidad) 
        references Disponibilidad

    alter table POIS_Disponibilidad 
        add constraint FK_rkk3d248e9gp8hf0hn7wuw2ei 
        foreign key (POIS_poiID) 
        references POIS

    alter table PalabrasClave 
        add constraint FK_hs25movjb81ohx3a4gq6gl1b8 
        foreign key (Poi_poiID) 
        references POIS

    alter table ServiciosCGP_Disponibilidad 
        add constraint FK_sc7sk0ooswmxqt8swjv4sc97v 
        foreign key (horariosDeAtencion_idDisponibilidad) 
        references Disponibilidad

    alter table ServiciosCGP_Disponibilidad 
        add constraint FK_hwd7ks0h0pe4b5n9p690ohe0v 
        foreign key (ServiciosCGP_idServicioCGP) 
        references ServiciosCGP

    alter table Ubicacion 
        add constraint FK_oikmk409p3l8ed4iwjt3ahaqe 
        foreign key (domicilio_domicilioID) 
        references Domicilio

    alter table Ubicacion 
        add constraint FK_g8k3mkhl5i8ox94kbbjq0xe7l 
        foreign key (region_RegionID) 
        references Region
