
    create table Domicilios (
        domicilioID bigint generated by default as identity (start with 1),
        alturaCalles integer not null,
        alturaPrincipal integer not null,
        callePrincipal varchar(255),
        codigoPostal integer not null,
        departamento integer not null,
        entreUnaCalle varchar(255),
        hastaOtraCalle varchar(255),
        piso integer not null,
        unidad integer not null,
        primary key (domicilioID)
    )

    create table POIS (
        poiID bigint generated by default as identity (start with 1),
        nombre varchar(255),
        domicilio_domicilioID bigint,
        primary key (poiID)
    )

    alter table POIS 
        add constraint FK_in2a3eywcqh7ppriwxupg749y 
        foreign key (domicilio_domicilioID) 
        references Domicilios
